<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMQl76dm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMQl76dm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMQl76dm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMQl76dm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMQl76dm\App_KernelDevDebugContainer([
    'container.build_hash' => 'MQl76dm',
    'container.build_id' => 'b5f3a6bc',
    'container.build_time' => 1779387180,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMQl76dm');
